### ISSUE TITLE
Layout_To_Do

### ISSUE THREAD

**Issue by blythethea** [blythethea/in_corporeal#2]
- [x] Center Nav (Peter)
- [x] remove footer (Peter)
- [x] remove decription text (Peter)
- [ ] add contact form (Peter)

**Comment by DeckardKane** [comment]
Regarding the footer, do you not want a footer at all? Like, ever?

**Comment by DeckardKane** [comment]
Centered nav is now functional, the footer is no longer on the home page, and the description text has been changed, @blythethea should change it further in _config.yml, because it's important, it's what will show up when you google this site. If you don't want it to show in the footer at all, we can discuss that, but first change it to your liking.

**Comment by DeckardKane** [comment]
Finally, adding a contact form will take much longer, and I'm going to make it into its own issue. Closing this issue as the other tasks are complete!
